# -*- coding: utf-8 -*-
"""CENSUS-B5 stories.jsonl 生成器：52 Story（R08+R09）× Sweep Log S1-S11
逐项映射（program / premise / param / excluded / eo / sn / tar）+ Surface
四面判定。盲段产物（registry 未读）。本批无 0 程序边界样本（BFS 型）——
52/52 双面程序（Bake+Response）；9 例 Response 为 P04 guard 双 Path。"""
import json
from pathlib import Path

BATCH_DIR = Path(__file__).parent

# 映射值域同 B4：
#  program:<pid> / premise-><pid> / param-><pid> / excluded:<reason> / eo_no_program / sn / tar:<id>
PROG = "program:"
PREM = "premise->"
PAR = "param->"
EXC = "excluded:"
EO = "eo_no_program"
SN = "sn"

SRC = "https://app.notion.com/p/3d7a4137d23681"
URLS = {
    # R08
    "SAF": SRC+"119b6aaf8457de89541", "ARO": SRC+"1f2b556def8bd21ff9a",
    "CSL": SRC+"1d3a9c6ca05ecbadac6", "AKB": SRC+"15ebb30d511f8bab74b",
    "MHS": SRC+"181a4d4fdd6f64bebcd", "SPM": SRC+"179bf16e7b791f5ab3f",
    "YFT": SRC+"1d888a4cd74dce4054a", "STM": SRC+"17999923cd392bfc0f0a",
    "ALB": SRC+"181a585d84a7f8aa4b4", "STL": SRC+"1f28078f0a1e7e33d7a",
    "ARG": SRC+"1c49e17eb4573c4c867", "LKT": SRC+"145b413ff9f36b5ac8e",
    "RHM": SRC+"17eb518fae0be954105", "RBP": SRC+"1018e5fceb06333f0d5",
    "TMU": SRC+"133bf92dec11cd68662", "SPK": SRC+"17c84b1fa57bdf2f261",
    "DTN": SRC+"1b0b2c9d9b4412ad818", "GAJ": SRC+"193a31defe1eca576cb",
    "HAD": SRC+"107afcbf98c58e257a0", "BPB": SRC+"1e6a00fdd24fdca6535",
    "RVC": SRC+"12da391def70534e735", "CRC": SRC+"150beaaef2c28407ff4",
    "INC": SRC+"1c9bbb9c6c60cc3671d", "HBW": SRC+"145bce1f564a311de52",
    "CLC": SRC+"1d6b645f7b5bc07a13b", "RTC": SRC+"1098c55e5705ef95962",
    # R09
    "WST": SRC+"13187adddcd69543f07", "ROB": SRC+"118a72cf8959f9bd1b0",
    "KGO": SRC+"1b68b31d8c5b9599e00", "LMD": SRC+"1bb8fd0d8734eb329b2",
    "MDC": SRC+"1bdb8d9caf7e494d0a4", "JGC": SRC+"184a040d081eee7d919",
    "SPC": SRC+"187ad00e324e1380b54", "TGT": SRC+"1d79933d7ffd8993431",
    "HYC": SRC+"1f2ad7ee79384e1e421", "PRC": SRC+"176a3e3dd6402dae8ba",
    "CCR": SRC+"191b66eed0bad664c99", "APA": SRC+"19db21adddce653b2e1",
    "GOT": SRC+"18bbf6dc0f9aedb4643", "GIT": SRC+"12a8564fe14934880c6",
    "SVT": SRC+"12c94eef4acbd36b2c0", "PEL": SRC+"1698c3ec857e0f936ba",
    "CMR": SRC+"1d8a4a9d0fc32c41407", "LKR": SRC+"152a0ecd8b5939cab48",
    "ASP": SRC+"1ea892ffc8e9715678f", "BIA": SRC+"1698a9cc1805a8f7425",
    "HLL": SRC+"183a3f2d34097ae916e", "BAS": SRC+"1459c6afea8475b6ad5",
    "JDP": SRC+"11ebb5aefb0cbcac9a0", "LMP": SRC+"11ebec0cc6c0640ef44",
    "AMK": SRC+"19d8b05fa1bb6a6f16e", "GSF": SRC+"1a99a88d40a0a11075b",
}

EO_DIET = ("eo_no_program：食性机制细节 EO——Response 程序体由 P01 PatternFit+"
           "TargetFeeding channel 冻结主张承载（MEDIUM，同属/同科/亲本/形态推断），"
           "引文闭合归 FR 线")

SWEEPS = {
 # S1 食性 | S2 形态机制 | S3 群游 | S4 温度/季节 | S5 洄游 | S6 繁殖 | S7 感官 | S8 栖息 | S9 体型/发育 | S10 游钓 | S11 反捕食/边界
 "SAF": {"S1": PROG+"P-B5-SAF-RESP", "S2": PAR+"P-B5-SAF-RESP（喙击打攻击工具 typed——改造目标可捕获性非生成机会）",
         "S3": PAR+"P-B5-SAF-RESP（猎物群游取向 typed context）", "S4": SN, "S5": PREM+"P-B5-SAF-BAKE",
         "S6": EXC+"batch 产卵=lifecycle premise 无护", "S7": PAR+"P-B5-SAF-RESP（帆展开攻击姿态 overlay+喙）",
         "S8": PROG+"P-B5-SAF-BAKE", "S9": SN, "S10": EXC+"billfish 游钓传统=产品面（Hemingway 文化注记）",
         "S11": SN},
 "ARO": {"S1": PROG+"P-B5-ARO-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-ARO-RESP（P04 口哺携带型 guard 双 Path）",
         "S7": PAR+"P-B5-ARO-RESP（上口位+跳出水面呈现 typed）", "S8": PROG+"P-B5-ARO-BAKE",
         "S9": SN, "S10": EO, "S11": SN},
 "CSL": {"S1": PROG+"P-B5-CSL-RESP", "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-CSL-BAKE（冻结/干涸钻泥蛰伏=P05 状态 premise）", "S5": SN,
         "S6": PROG+"P-B5-CSL-RESP（P04 雄护卵+浮游幼双 Path）", "S7": EO,
         "S8": PROG+"P-B5-CSL-BAKE", "S9": SN, "S10": SN,
         "S11": EXC+"入侵欧洲 extirpate=生态影响注记（Story Open 供给语义），非程序面"},
 "AKB": {"S1": EO_DIET, "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-AKB-BAKE（温升 10-15°C 产卵触发 premise）",
         "S5": PREM+"P-B5-AKB-BAKE（上溯）", "S6": EXC+"batch spawner=lifecycle premise",
         "S7": EO, "S8": PROG+"P-B5-AKB-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "MHS": {"S1": PROG+"P-B5-MHS-RESP", "S2": EO, "S3": SN, "S4": SN, "S5": SN,
         "S6": EXC+"成对草丛产卵=lifecycle premise 无护", "S7": EO,
         "S8": PROG+"P-B5-MHS-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "SPM": {"S1": PROG+"P-B5-SPM-RESP", "S2": SN,
         "S3": EXC+"单独猎击（hunts alone）=负知识：非群游协作不构群结构供给",
         "S4": SN, "S5": PREM+"P-B5-SPM-BAKE", "S6": EXC+"batch 无护=lifecycle",
         "S7": EO, "S8": PROG+"P-B5-SPM-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "YFT": {"S1": PROG+"P-B5-YFT-RESP", "S2": SN,
         "S3": EXC+"体型分级群游（school primarily by size）+海豚/漂浮物关联=群结构"
                "事实/FAD 型遇鱼分布≠互斥 FishGroup（B3 CHU/B4 CBM 同型判例）",
         "S4": SN, "S5": PREM+"P-B5-YFT-BAKE", "S6": EXC+"batch 产卵=lifecycle",
         "S7": EO, "S8": PROG+"P-B5-YFT-BAKE",
         "S9": EXC+"体型分级=群结构事实（S3 同源）非摄食程序参数", "S10": EO, "S11": SN},
 "STM": {"S1": PROG+"P-B5-STM-RESP", "S2": EO, "S3": PAR+"P-B5-STM-RESP（猎物群游取向）",
         "S4": SN, "S5": PREM+"P-B5-STM-BAKE", "S6": EXC+"batch 无护=lifecycle",
         "S7": EO, "S8": PROG+"P-B5-STM-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "ALB": {"S1": PROG+"P-B5-ALB-RESP", "S2": SN,
         "S3": EXC+"混群（skipjack/yellowfin/bluefin）+马尾藻漂浮物=多物种同场供给"
                "群结构事实≠互斥 FishGroup（YFT 同型）",
         "S4": SN, "S5": PREM+"P-B5-ALB-BAKE", "S6": EXC+"雌雄分离分布=lifecycle 分布 premise",
         "S7": EO, "S8": PROG+"P-B5-ALB-BAKE", "S9": EXC+"成鱼雄多=种群结构背景",
         "S10": EXC+"游钓事实（strike hard and make powerful runs FishBase 原文）=搏鱼阶段产品面",
         "S11": SN},
 "STL": {"S1": PROG+"P-B5-STL-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-STL-BAKE（可重复溯河=生活史策略 premise）",
         "S6": EXC+"多次产卵 iteroparity=lifecycle 节奏", "S7": EO,
         "S8": PROG+"P-B5-STL-BAKE",
         "S9": EXC+"同种双型=生活史策略非 Group（P05：真实生命周期差异≠必须预分供给）",
         "S10": EXC+"游钓文化价值=产品面", "S11": SN},
 "ARG": {"S1": PROG+"P-B5-ARG-RESP", "S2": SN,
         "S3": EXC+"群游=非生殖集群背景非互斥 FishGroup", "S4": SN,
         "S5": PREM+"P-B5-ARG-BAKE（季节领土/下游移动）",
         "S6": EXC+"背鳍求偶展示=繁殖信号非捕食程序；无 redd=产卵行为变量（lifecycle）",
         "S7": PAR+"P-B5-ARG-RESP（水面呈现 typed——surface insects+落水旅鼠）",
         "S8": PROG+"P-B5-ARG-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "LKT": {"S1": PROG+"P-B5-LKT-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": SN, "S6": EXC+"夜行产卵+雄先到清岩=繁殖时段/产卵准备行为（lifecycle）非护巢持续证据",
         "S7": PAR+"P-B5-LKT-RESP（夜行=低光 typed context，R03 先例不买 Night Mode）",
         "S8": PROG+"P-B5-LKT-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "RHM": {"S1": PROG+"P-B5-RHM-RESP（植物叶取食 FishBase 原文承载）", "S2": SN,
         "S3": SN, "S4": SN, "S5": SN, "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-RHM-BAKE（悬岸植被=ResourcePatch P02 背景语义）",
         "S9": SN, "S10": SN, "S11": SN},
 "RBP": {"S1": PROG+"P-B5-RBP-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-RBP-BAKE（potamodromous）", "S6": SN,
         "S7": EXC+"幼体拟态红腹食人鱼=反捕食策略非摄食程序", "S8": PROG+"P-B5-RBP-BAKE",
         "S9": EXC+"幼拟态=反捕食（S7 同源 ontogeny premise）", "S10": EO, "S11": SN},
 "TMU": {"S1": PROG+"P-B5-TMU-RESP（狗鱼系伏击复用 MEDIUM）", "S2": SN, "S3": SN,
         "S4": SN, "S5": EXC+"人工投放=非自然洄游（供给层注记 Story Open）", "S6": SN,
         "S7": EO, "S8": PROG+"P-B5-TMU-BAKE（亲本型栖息复用）",
         "S9": EXC+"杂种优势快生长=生长变量（身份层 Identity-Deferred）",
         "S10": EXC+"投放游钓供给=产品面", "S11": SN},
 "SPK": {"S1": PROG+"P-B5-SPK-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": SN, "S6": EO, "S7": EO, "S8": PROG+"P-B5-SPK-BAKE",
         "S9": PREM+"P-B5-SPK-RESP（幼-成相食 ontogeny premise）", "S10": EO, "S11": SN},
 "DTN": {"S1": PROG+"P-B5-DTN-RESP", "S2": SN, "S3": PAR+"P-B5-DTN-RESP（猎物群游取向 typed）",
         "S4": SN, "S5": SN, "S6": SN, "S7": EO, "S8": PROG+"P-B5-DTN-BAKE",
         "S9": SN, "S10": EO,
         "S11": EXC+"ciguatoxic=人类侧食物安全 Capture Boundary（CB 轴，R07 补标系判例第 3 例）"},
 "GAJ": {"S1": PROG+"P-B5-GAJ-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PREM+"P-B5-GAJ-BAKE（夏季近岸产卵=季节繁殖 premise 重排）", "S7": EO,
         "S8": PROG+"P-B5-GAJ-BAKE", "S9": SN, "S10": EO,
         "S11": EXC+"ciguatera=人类侧食物安全 CB 轴（同 DTN）"},
 "HAD": {"S1": PROG+"P-B5-HAD-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EXC+"batch 产卵=lifecycle premise", "S7": EO, "S8": PROG+"P-B5-HAD-BAKE",
         "S9": SN, "S10": EO, "S11": SN},
 "BPB": {"S1": PROG+"P-B5-BPB-RESP", "S2": SN,
         "S3": EXC+"成群=遇鱼分布背景非互斥 FishGroup", "S4": SN,
         "S5": SN, "S6": EO, "S7": EO, "S8": PROG+"P-B5-BPB-BAKE", "S9": SN,
         "S10": EO, "S11": SN},
 "RVC": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EO, "S7": EO, "S8": PROG+"P-B5-RVC-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "CRC": {"S1": PROG+"P-B5-CRC-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-CRC-RESP（P04 砾巢脊 guard 双 Path——石巢系第 3 例异属重复）",
         "S7": EO, "S8": PROG+"P-B5-CRC-BAKE",
         "S9": PREM+"P-B5-CRC-RESP（幼无脊椎→成鱼/螯虾 ontogeny premise）", "S10": SN, "S11": SN},
 "INC": {"S1": PROG+"P-B5-INC-RESP", "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-INC-BAKE（融冰触发上溯）",
         "S5": PREM+"P-B5-INC-BAKE（停食溯河=P05 状态抑制 Feeding Path——停食洄游第 3 例）",
         "S6": EXC+"黄昏夜产+2-4 年一次=lifecycle 节奏 premise", "S7": EO,
         "S8": PROG+"P-B5-INC-BAKE", "S9": PREM+"P-B5-INC-RESP（幼-成食性 ontogeny）",
         "S10": EO, "S11": SN},
 "HBW": {"S1": PROG+"P-B5-HBW-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-HBW-BAKE（1200km 溯河+部分不出海双型）", "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-HBW-BAKE", "S9": PREM+"P-B5-HBW-BAKE（幼 4-6 年返回阶段 premise）",
         "S10": SN, "S11": SN},
 "CLC": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN, "S6": EO,
         "S7": EO, "S8": PROG+"P-B5-CLC-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "RTC": {"S1": PROG+"P-B5-RTC-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-RTC-BAKE（potamodromous）", "S6": EO, "S7": EO,
         "S8": PROG+"P-B5-RTC-BAKE", "S9": SN,
         "S10": EXC+"南美游钓名鱼 pirarara=产品面事实", "S11": SN},
 # ---------------- R09 ----------------
 "WST": {"S1": PROG+"P-B5-WST-RESP（体型分级鱼食）", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-WST-BAKE（海-河洄游+产卵前停食=P05 状态抑制第 4 例）",
         "S6": EXC+"4-11 年产卵间隔=lifecycle 节奏 premise", "S7": EO,
         "S8": PROG+"P-B5-WST-BAKE", "S9": PREM+"P-B5-WST-RESP（>48.3cm 鱼食 ontogeny premise）",
         "S10": EO, "S11": EXC+"VU/CITES II 保护边界=OPS 产品供给面（B3 AST 先例）"},
 "ROB": {"S1": PROG+"P-B5-ROB-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-ROB-RESP（P04 雄巢扇护 guard 双 Path+一巢多雌）", "S7": EO,
         "S8": PROG+"P-B5-ROB-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "KGO": {"S1": PROG+"P-B5-KGO-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN, "S6": SN,
         "S7": EO, "S8": PROG+"P-B5-KGO-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "LMD": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN, "S6": EO, "S7": EO,
         "S8": PROG+"P-B5-LMD-BAKE（同属岩区推断）", "S9": SN, "S10": SN, "S11": SN},
 "MDC": {"S1": PROG+"P-B5-MDC-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-MDC-RESP（P04 洞顶产卵双亲 guard 双 Path）", "S7": EO,
         "S8": PROG+"P-B5-MDC-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "JGC": {"S1": PROG+"P-B5-JGC-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-JGC-RESP（P04 双亲护卵幼 guard 双 Path）", "S7": EO,
         "S8": PROG+"P-B5-JGC-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "SPC": {"S1": PROG+"P-B5-SPC-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EO, "S7": EO, "S8": PROG+"P-B5-SPC-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "TGT": {"S1": PROG+"P-B5-TGT-RESP（亲本系 P01 复用 MEDIUM）", "S2": SN, "S3": SN,
         "S4": SN, "S5": EXC+"人工投放=非自然洄游（供给层）", "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-TGT-BAKE（亲本系栖息复用）", "S9": EXC+"杂种优势=身份层注记",
         "S10": EO, "S11": SN},
 "HYC": {"S1": PROG+"P-B5-HYC-RESP（鲫系 P01 复用 MEDIUM）", "S2": SN, "S3": SN,
         "S4": SN, "S5": SN, "S6": EXC+"三倍体不育=lifecycle premise", "S7": EO,
         "S8": PROG+"P-B5-HYC-BAKE（鲫系底栖复用）", "S9": EXC+"三倍体=身份层注记",
         "S10": SN, "S11": SN},
 "PRC": {"S1": PROG+"P-B5-PRC-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EXC+"雌核发育+精寄生=繁殖系统变量 premise（R09 FR：非呈现轴）", "S7": EO,
         "S8": PROG+"P-B5-PRC-BAKE", "S9": EXC+"三倍全雌=种群结构注记", "S10": SN, "S11": SN},
 "CCR": {"S1": PROG+"P-B5-CCR-RESP", "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-CCR-BAKE（干冬钻泥=P05 蛰伏状态第 5 例）", "S5": SN,
         "S6": SN, "S7": PAR+"P-B5-CCR-RESP（夜行=低光 typed context，R03 先例）",
         "S8": PROG+"P-B5-CCR-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "APA": {"S1": PROG+"P-B5-APA-RESP（山地溪流食性栖息推断承载 MEDIUM）", "S2": SN,
         "S3": SN, "S4": SN, "S5": SN, "S6": SN, "S7": EO, "S8": PROG+"P-B5-APA-BAKE",
         "S9": SN, "S10": EO, "S11": EO},
 "GOT": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN, "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-GOT-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "GIT": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN, "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-GIT-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "SVT": {"S1": PROG+"P-B5-SVT-RESP（端足类专食）", "S2": SN, "S3": SN, "S4": SN,
         "S5": EXC+"湖内季节移动非洄游=负知识（P05 季节 premise）",
         "S6": EXC+"双种群季节分离产卵=lifecycle premise", "S7": EO,
         "S8": PROG+"P-B5-SVT-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "PEL": {"S1": PROG+"P-B5-PEL-RESP（三态食性 breadth typed）", "S2": SN, "S3": SN,
         "S4": SN, "S5": PREM+"P-B5-PEL-BAKE（湖-河-溯河三型生活史 premise）", "S6": SN,
         "S7": EO, "S8": PROG+"P-B5-PEL-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "CMR": {"S1": PROG+"P-B5-CMR-RESP", "S2": SN,
         "S3": EXC+"浅水植被群产=繁殖集群非摄食 FishGroup（B3 BUR 同型判例）",
         "S4": SN, "S5": SN, "S6": EXC+"粘卵无护=lifecycle 无 P04",
         "S7": EO, "S8": PROG+"P-B5-CMR-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "LKR": {"S1": PROG+"P-B5-LKR-RESP（同种复用）", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": SN, "S7": EO, "S8": PROG+"P-B5-LKR-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "ASP": {"S1": PROG+"P-B5-ASP-RESP", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-ASP-BAKE（4-6 月上游产卵迁移）",
         "S6": EXC+"粘卵无护=lifecycle 无 P04",
         "S7": PAR+"P-B5-ASP-RESP（水面呈现 typed——小水鸟落水输入）",
         "S8": PROG+"P-B5-ASP-BAKE（桥墩/堰坝结构伏击位点）",
         "S9": PREM+"P-B5-ASP-RESP（幼-成鱼食 ontogeny premise）", "S10": EO, "S11": SN},
 "BIA": {"S1": PROG+"P-B5-BIA-RESP（獠牙掠食推断 MEDIUM）", "S2": SN, "S3": SN, "S4": SN,
         "S5": PREM+"P-B5-BIA-BAKE（potamodromous）", "S6": EO, "S7": EO,
         "S8": PROG+"P-B5-BIA-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "HLL": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EXC+"成对草丛产卵=lifecycle premise 无护", "S7": EO,
         "S8": PROG+"P-B5-HLL-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "BAS": {"S1": PROG+"P-B5-BAS-RESP", "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-BAS-BAKE（洪泛季初产卵=P05 洪水系 premise）",
         "S5": PREM+"P-B5-BAS-BAKE（成鱼入洪泛林）", "S6": SN, "S7": EO,
         "S8": PROG+"P-B5-BAS-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "JDP": {"S1": PROG+"P-B5-JDP-RESP", "S2": SN, "S3": SN,
         "S4": PREM+"P-B5-JDP-BAKE（洪水事件机会繁殖=P05 洪水系第 3 例）", "S5": SN,
         "S6": PROG+"P-B5-JDP-RESP（P04 雄护卵 guard 双 Path）", "S7": EO,
         "S8": PROG+"P-B5-JDP-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "LMP": {"S1": PROG+"P-B5-LMP-RESP", "S2": PAR+"P-B5-LMP-BAKE（吸盘形态=底栖附着 typed context）",
         "S3": SN, "S4": PREM+"P-B5-LMP-BAKE（深冬浅夏季节 premise）",
         "S5": PREM+"P-B5-LMP-BAKE（季节洄游）",
         "S6": PROG+"P-B5-LMP-RESP（P04 雄激进护卵块 guard 双 Path）",
         "S7": PAR+"P-B5-LMP-RESP（雌雄二态色=呈现变量 typed context）",
         "S8": PROG+"P-B5-LMP-BAKE", "S9": SN, "S10": SN, "S11": SN},
 "AMK": {"S1": EO_DIET, "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": PROG+"P-B5-AMK-RESP（P04 雄岩缝扇护 guard 双 Path+一年两产节奏）",
         "S7": EO, "S8": PROG+"P-B5-AMK-BAKE", "S9": SN, "S10": EO, "S11": SN},
 "GSF": {"S1": PROG+"P-B5-GSF-RESP", "S2": SN, "S3": SN, "S4": SN, "S5": SN,
         "S6": EO, "S7": EO, "S8": PROG+"P-B5-GSF-BAKE",
         "S9": PREM+"P-B5-GSF-RESP（幼食未成熟虫/微型甲壳 ontogeny premise）",
         "S10": EO, "S11": SN},
}

GROUP_NO = {
 "SAF": "海洋分布广域；无互斥供给主张（S3=猎物群游 param）",
 "ARO": "无集群主张（S3 SN）", "CSL": "无集群主张（S3 SN）",
 "AKB": "无集群主张（S3 SN）", "MHS": "无集群主张（S3 SN）",
 "SPM": "单独猎击=负知识：非群游协作不构群结构供给",
 "YFT": "体型分级群游+海豚/漂浮物 FAD 关联=群结构事实≠互斥 FishGroup（CBM 同型判例）",
 "STM": "无集群主张（S3=猎物群游 param）",
 "ALB": "混群+马尾藻=多物种同场供给群结构事实≠互斥 FishGroup",
 "STL": "同种双型不拆 Group（遗传同种——P05 判例）",
 "ARG": "群游=非生殖集群背景", "LKT": "无集群主张（S3 SN）",
 "RHM": "无集群主张（S3 SN）", "RBP": "无集群主张（S3 SN）",
 "TMU": "无集群主张（投放种群结构=人工引入注记）", "SPK": "无集群主张（S3 SN）",
 "DTN": "无集群主张（S3=猎物群游 param）", "GAJ": "无集群主张（S3 SN）",
 "HAD": "无集群主张（S3 SN）", "BPB": "成群=遇鱼分布背景非 Group 程序",
 "RVC": "无集群主张（S3 SN）", "CRC": "无集群主张（S3 SN）",
 "INC": "无集群主张（S3 SN）", "HBW": "双型不拆 Group（P05）",
 "CLC": "无集群主张（S3 SN）", "RTC": "无集群主张（S3 SN）",
 "WST": "无集群主张（S3 SN）", "ROB": "无集群主张（S3 SN）",
 "KGO": "无集群主张（S3 SN）", "LMD": "无集群主张（S3 SN）",
 "MDC": "无集群主张（S3 SN）", "JGC": "无集群主张（S3 SN）",
 "SPC": "无集群主张（S3 SN）", "TGT": "无集群主张（S3 SN）",
 "HYC": "无集群主张（S3 SN）", "PRC": "全雌种群=种群结构注记非 Group",
 "CCR": "无集群主张（S3 SN）", "APA": "无集群主张（S3 SN）",
 "GOT": "无集群主张（S3 SN）", "GIT": "无集群主张（S3 SN）",
 "SVT": "双种群分离=同种空间时间分离 premise 非 Group",
 "PEL": "三型不拆 Group（P05：真实生命周期差异≠必须预分供给）",
 "CMR": "浅水植被群产=繁殖集群非摄食 FishGroup（BUR 同型判例）",
 "LKR": "无集群主张（S3 SN）", "ASP": "无集群主张（S3 SN）",
 "BIA": "无集群主张（S3 SN）", "HLL": "无集群主张（S3 SN）",
 "BAS": "无集群主张（S3 SN）", "JDP": "无集群主张（S3 SN）",
 "LMP": "独居=负知识（S3 SN 非群游）", "AMK": "群游假说 EO 不构群结构主张",
 "GSF": "无集群主张（S3 SN）",
}
QUALITY_NO = "无 Quality Selection 程序证据（同 B0-B4 基线）"

PATTERNS = {
 "SAF": ["P01","P05"], "ARO": ["P01","P04"], "CSL": ["P01","P04","P05"],
 "AKB": ["P01"], "MHS": ["P01"], "SPM": ["P01","P05"], "YFT": ["P01","P05"],
 "STM": ["P01","P05"], "ALB": ["P01","P05"], "STL": ["P01","P05"],
 "ARG": ["P01","P05"], "LKT": ["P01","P05"], "RHM": ["P01","P02"],
 "RBP": ["P01","P02"], "TMU": ["P01","ID-DEFER"], "SPK": ["P01"], "DTN": ["P01"],
 "GAJ": ["P01","P05"], "HAD": ["P01"], "BPB": ["P01"], "RVC": ["P01"],
 "CRC": ["P01","P04"], "INC": ["P01","P05"], "HBW": ["P01","P05"],
 "CLC": ["P01"], "RTC": ["P01"],
 "WST": ["P01","P05"], "ROB": ["P01","P04"], "KGO": ["P01"], "LMD": ["P01"],
 "MDC": ["P01","P04"], "JGC": ["P01","P04"], "SPC": ["P01"],
 "TGT": ["P01","ID-DEFER"], "HYC": ["P01","ID-DEFER"], "PRC": ["P01","P05"],
 "CCR": ["P01"], "APA": ["P01"], "GOT": ["P01"], "GIT": ["P01"],
 "SVT": ["P01","P05"], "PEL": ["P01","P05"], "CMR": ["P01"],
 "LKR": ["P01","ID-DEFER"], "ASP": ["P01","P05"], "BIA": ["P01"], "HLL": ["P01"],
 "BAS": ["P01","P05"], "JDP": ["P01","P04","P05"], "LMP": ["P01","P04","P05"],
 "AMK": ["P01","P04"], "GSF": ["P01"],
}
TITLE = {
 "SAF": "FISH-R08｜旗鱼｜Sailfish｜Bill-Striking School Hunter",
 "ARO": "FISH-R08｜银龙鱼｜Silver Arowana｜Surface-Jump Feeder + Male Mouthbrooder",
 "CSL": "FISH-R08｜葛氏鲈塘鳢｜Chinese Sleeper｜Frozen-Dormancy Pond Ambusher",
 "AKB": "FISH-R08｜阿拉斯加黑鱼｜Alaska Blackfish｜Esophagus-Breathing Freeze Survivor",
 "MHS": "FISH-R08｜大理石倒立鱼｜Marbled Headstander｜Head-Down Posture Hypothesis",
 "SPM": "FISH-R08｜康氏马鲛｜Spanish Mackerel｜Solo Fast-Strike Coastal Hunter",
 "YFT": "FISH-R08｜黄旗金枪鱼｜Yellowfin Tuna｜Size-School Dolphin-Associated Oceanic",
 "STM": "FISH-R08｜条纹四鳍旗鱼｜Striped Marlin｜Cooler-Water Billfish",
 "ALB": "FISH-R08｜长鳍金枪鱼｜Albacore｜Mixed-School Runfighter",
 "STL": "FISH-R08｜硬头鳟｜Steelhead｜Same-Species Dual Life-History Iteroparous",
 "ARG": "FISH-R08｜北极茴鱼｜Arctic Grayling｜Surface-Insect Sail-Fin Display",
 "LKT": "FISH-R08｜湖红点鲑｜Lake Trout｜Deep-Lake Night-Spawner",
 "RHM": "FISH-R08｜红钩鱼｜Redhook Myleus｜Herbivore-in-Piranha-Family",
 "RBP": "FISH-R08｜淡水白鲳｜Red-bellied Pacu｜Juvenile-Mimic Herbivore",
 "TMU": "FISH-R08｜虎纹梭鱼｜Tiger Muskellunge｜Sterile-Hybrid Stocked Sportfish",
 "SPK": "FISH-R08｜萨克拉门托大斑狗鱼｜Sacramento Pikeminnow｜Misnamed-Cyprinid Predator",
 "DTN": "FISH-R08｜裸狐鲣｜Dogtooth Tuna｜Reef-Resident Tuna Contrarian",
 "GAJ": "FISH-R08｜高体鰤｜Greater Amberjack｜Deep-Reef Summer Spawner",
 "HAD": "FISH-R08｜黑线鳕｜Haddock｜Mid-Depth Bottom Forager",
 "BPB": "FISH-R08｜眼点丽鱼｜Butterfly Peacock Bass｜Exclusive Piscivore Cichlid",
 "RVC": "FISH-R08｜小须美鱥｜River Chub｜Nocomis Congeneric Default",
 "CRC": "FISH-R08｜黑斑须雅罗鱼｜Creek Chub｜Gravel-Ridge Nest Builder",
 "INC": "FISH-R08｜白北鲑｜Inconnu｜Fasting-Run Ice-Break Spawner",
 "HBW": "FISH-R08｜驼背白鲑｜Humpback Whitefish｜Dual-Migration Whitefish",
 "CLC": "FISH-R08｜大口鲶｜Chinese Largemouth Catfish｜Silurus Congeneric Default",
 "RTC": "FISH-R08｜红尾鲶鱼｜Redtail Catfish｜Pirarara Sport Catfish",
 "WST": "FISH-R09｜高首鲟｜White Sturgeon｜Giant Anadromous Sturgeon",
 "ROB": "FISH-R09｜岩钝鲈｜Rock Bass｜Rock-Pool Nest Guarder",
 "KGO": "FISH-R09｜接吻鲷｜Kissing Gourami｜Lip-Kissing Omnivore",
 "LMD": "FISH-R09｜斑鳜｜Leopard Mandarin Fish｜Congeneric Ambush Default",
 "MDC": "FISH-R09｜米达斯慈鲷｜Midas Cichlid｜Cave-Ceiling Biparental Guarder",
 "JGC": "FISH-R09｜淡水石斑｜Jaguar Cichlid｜Turbid-Lake Biparental Predator",
 "SPC": "FISH-R09｜金目丽鱼｜Speckled Peacock｜Cichla Congeneric 3rd",
 "TGT": "FISH-R09｜虎纹鳟鱼｜Tiger Trout｜Sterile-Hybrid Salmonid 2nd",
 "HYC": "FISH-R09｜工程鲫｜Hybrid Crucian｜Triploid Engineered Identity",
 "PRC": "FISH-R09｜银鲫｜Prussian Carp｜Gynogenetic All-Female",
 "CCR": "FISH-R09｜金鲫｜Crucian Carp｜Night-Bottom Mud-Burrower",
 "APA": "FISH-R09｜阿帕奇鳟鱼｜Apache Trout｜Endangered Headwater Native",
 "GOT": "FISH-R09｜金鳟｜Golden Trout｜High-Elevation Endemic",
 "GIT": "FISH-R09｜吉拉鳟鱼｜Gila Trout｜Endangered Headwater 3rd",
 "SVT": "FISH-R09｜塞凡湖鳟｜Sevan Trout｜Lake-Endemic Dual-Stock Specialist",
 "PEL": "FISH-R09｜高白鲑｜Peled｜Tri-Form Whitefish 5th",
 "CMR": "FISH-R09｜常见拟鲤｜Common Roach｜Duplicate-Row Cyprinid A",
 "LKR": "FISH-R09｜湖拟鲤｜Roach｜Duplicate-Row Cyprinid B",
 "ASP": "FISH-R09｜赤稍雅罗鱼｜Asp｜Rare-Cyprinid Piscivore",
 "BIA": "FISH-R09｜针牙脂鲤｜Biara｜Dogtooth Characid 2nd",
 "HLL": "FISH-R09｜黑带兔脂鲤｜Halfline Leporinus｜Headstander Congeneric 2nd",
 "BAS": "FISH-R09｜巨型巴沙｜Basa｜Flood-Pulse Air-Breathing Pangasiid",
 "JDP": "FISH-R09｜宝石鲈｜Jade Perch｜Flood-Opportunity Guarder",
 "LMP": "FISH-R09｜圆鳍鱼｜Lumpfish｜Sucker-Disc Egg-Guarder",
 "AMK": "FISH-R09｜单鳍多线鱼｜Atka Mackerel｜Rock-Crevice Fan-Guarder",
 "GSF": "FISH-R09｜绿太阳鱼｜Green Sunfish｜Sunfish Congeneric 5th",
}

GUARD_9 = {"ARO", "CSL", "CRC", "ROB", "MDC", "JGC", "JDP", "LMP", "AMK"}


def story_rec(sid):
    resp_reason = ("P04 guard 双 Path（food ∥ conflict → COMBINE）"
                   if sid in GUARD_9 else "P01 typed 离散目标响应")
    surfaces = {
        "Group": {"consequence": "NO_SURFACE_EFFECT", "reason": GROUP_NO[sid]},
        "Bake": {"consequence": "NEW_PROGRAM_CANDIDATE",
                 "program_ids": [f"P-B5-{sid}-BAKE"],
                 "reason": "栖息/周期空间因子程序证据（S8 MSF 全 52 例）"},
        "Response": {"consequence": "NEW_PROGRAM_CANDIDATE",
                     "program_ids": [f"P-B5-{sid}-RESP"],
                     "reason": resp_reason},
        "Quality": {"consequence": "NO_SURFACE_EFFECT", "reason": QUALITY_NO},
    }
    rec = {
        "story_id": f"CENSUS-B5-{sid}", "source_story": TITLE[sid],
        "story_url": URLS[sid],
        "frozen_patterns": PATTERNS[sid],
        "sweep_log_mapping": SWEEPS[sid],
        "surfaces": surfaces,
        "consequence": "NEW_PROGRAM_CANDIDATE",
        "provenance": {"batch": "CENSUS-B5"},
    }
    return rec


def main():
    out = BATCH_DIR / "stories.jsonl"
    recs = [story_rec(sid) for sid in SWEEPS]
    out.write_text("\n".join(json.dumps(r, ensure_ascii=False) for r in recs) + "\n",
                   encoding="utf-8")
    n_prog = sum(1 for r in recs for s in r["surfaces"].values()
                 if s["consequence"] == "NEW_PROGRAM_CANDIDATE")
    n_sweep = sum(len(r["sweep_log_mapping"]) for r in recs)
    print(f"wrote {len(recs)} stories; program-bearing surfaces={n_prog}; "
          f"sweep items={n_sweep}")


if __name__ == "__main__":
    main()
